### ISSUE TITLE
cannot run the Example script you provided

### ISSUE THREAD

**Issue by dylanwuyoufu** [tomquirk/realestate-com-au-api#1]
just got error from command line:
---------------------------------
 Fajita.__init__(
TypeError: __init__() got an unexpected keyword argument 'cookie_directory'
------------------------------------

**Comment by james3927** [comment]
the fajita module by the same author doesn't have that cookie_directory parameter
https://github.com/tomquirk/fajita/blob/master/fajita/fajita.py#L26

**Comment by tomquirk** [comment]
Thanks @dylanwuyoufu I'll take a look at this soon. Feel free to contribute a fix in Fajita if you like

**Comment by tomquirk** [comment]
Fixed!
