### ISSUE TITLE
No module named 'realestate_com_au'

### ISSUE THREAD

**Issue by Alperencode** [tomquirk/realestate-com-au-api#13]
Its still giving the `No module named 'realestate_com_au'` error whether I use the pip command you provided or not.

**Comment by tomquirk** [comment]
Did you get this working @Alperencode

**Comment by Alperencode** [comment]
@tomquirk Actually no, no-one contact with me so i did not put work on it.

**Comment by Alperencode** [comment]
It worked 👍🏿
